### ISSUE TITLE
Long time no update..

### ISSUE THREAD

**Issue by iambenmitchell** [mdsimmo/PistonCraft#1]
Hi, I am looking for a plugin that lets me increase the piston block limit. IE, moving 100 blocks

**Comment by mdsimmo** [comment]
Sorry, but this plugins not gonna get developed (unless you want to...)

Haven't tried these myself, but the following links would be your best bets:
Using sponge: https://forums.spongepowered.org/t/superpiston-allows-to-modify-vanilla-pistons/24164/2
Using spigot patches: https://blog.jorel.dev/Why-piston-limit-exists/
Using forge mods: https://www.curseforge.com/minecraft/mc-mods/redstoneplusplus
